SELECT CONCAT(NAME, '(', LEFT(OCCUPATION, 1), ')')
FROM OCCUPATIONS
ORDER BY NAME;

SELECT 'There are a total of', COUNT(OCCUPATION),
CASE
    WHEN OCCUPATION = 'DOCTOR' THEN 'doctors.'
    WHEN OCCUPATION = 'ACTOR' THEN 'actors.'
    WHEN OCCUPATION = 'SINGER' THEN 'singers.'
    ELSE 'professors.'
END AS OCCNAM
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;